"""create initial tables

Revision ID: e2b246866c67
Revises: 
Create Date: 2026-01-29 22:36:37.713348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b246866c67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_games',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('home_team', sa.String(length=10), nullable=False),
    sa.Column('away_team', sa.String(length=10), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_win', sa.Boolean(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('ix_historical_games_season_date', 'historical_games', ['season', 'game_date'], unique=False)
    op.create_index('ix_historical_games_teams_date', 'historical_games', ['home_team', 'away_team', 'game_date'], unique=False)
    op.create_table('historical_odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('point', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_odds_date_bookmaker', 'historical_odds', ['game_date', 'bookmaker'], unique=False)
    op.create_index(op.f('ix_historical_odds_game_id'), 'historical_odds', ['game_id'], unique=False)
    op.create_index('ix_historical_odds_game_timestamp', 'historical_odds', ['game_id', 'timestamp'], unique=False)
    op.create_index('ix_historical_odds_market_outcome_date', 'historical_odds', ['market', 'outcome', 'game_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_odds_market_outcome_date', table_name='historical_odds')
    op.drop_index('ix_historical_odds_game_timestamp', table_name='historical_odds')
    op.drop_index(op.f('ix_historical_odds_game_id'), table_name='historical_odds')
    op.drop_index('ix_historical_odds_date_bookmaker', table_name='historical_odds')
    op.drop_table('historical_odds')
    op.drop_index('ix_historical_games_teams_date', table_name='historical_games')
    op.drop_index('ix_historical_games_season_date', table_name='historical_games')
    op.drop_table('historical_games')
    # ### end Alembic commands ###
